name: build
permissions:
  contents: write
on: [create, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install env
        run: |
          sudo apt-get -qq install sbcl
          curl -o ~/quicklisp.lisp https://beta.quicklisp.org/quicklisp.lisp
          sbcl --load ~/quicklisp.lisp --eval '(quicklisp-quickstart:install)' --non-interactive
      - uses: actions/checkout@v1
      - name: Build the library
        run: |
          sbcl --noinform \
               --eval '(load "/home/runner/quicklisp/setup.lisp")' \
               --eval '(asdf:load-asd "/home/runner/work/redist/redist/redist.asd")' \
               --eval '(ql:quickload :redist)' \
               --non-interactive
      - name: Build the binary
        run: |
          sbcl --noinform \
               --eval '(load "/home/runner/quicklisp/setup.lisp")' \
               --eval '(asdf:load-asd "/home/runner/work/redist/redist/redist.asd")' \
               --eval '(asdf:make :redist)' \
               --non-interactive
      - name: Create release ZIP
        run: |
          zip -r redist-linux.zip redist template
      - name: Create release
        id: create_release
        uses: ncipollo/release-action@v1
        continue-on-error: true
        with:
          allowUpdates: true
          name: Release ${{ github.ref_name }}
          artifacts: redist-linux.zip

